In [8]:
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
from find_shifts import get_files, get_images, get_shifts
from skimage import registration, io
import cv2


In [2]:
g = get_files()
g

['movie\\-003.974_-012.883.jpg',
 'movie\\-003.974_-013.383.jpg',
 'movie\\-003.974_-013.883.jpg',
 'movie\\-004.474_-012.883.jpg',
 'movie\\-004.474_-013.383.jpg',
 'movie\\-004.474_-013.883.jpg',
 'movie\\-004.974_-012.883.jpg',
 'movie\\-004.974_-013.383.jpg',
 'movie\\-004.974_-013.883.jpg']

In [3]:
image_data = get_images(g)

In [9]:
shifts, error, phasediff = get_shifts(g, image_data)

[437. 470.   0.] 0.35411127860423913 2.8429691043996394e-19
[ 126. -579.    0.] 0.28256016523791716 -5.117081056798203e-19
[  2. 528.   0.] 0.2558952753031034 -4.0137950242142317e-19
[-433.  528.    0.] 0.27040597531864513 2.797981984486121e-19
[436.   1.   0.] 0.22293469413819902 3.653527058173935e-20
[  -2. -529.    0.] 0.20572924505074938 2.2754074448533963e-20
[-462.  539.    0.] 0.32689758560769006 -6.996331329724526e-19
[ -33. -138.    0.] 0.35913433261237543 9.41941340833239e-19
[0. 0. 0.] 2.1073424255447017e-08 0.0
[3. 0. 0.] 0.4289480794720797 -4.309193789170392e-19
[-458.   -6.    0.] 0.23854350253988743 3.6921318639949464e-19
[152.  74.   0.] 0.2880095593126611 1.1842892135135861e-19
[   3. -546.    0.] 0.30113302151267796 -3.509834545215746e-18
[0. 0. 0.] 5.960464477539063e-08 0.0
[-460. -535.    0.] 0.28088321745579903 3.1598053073549664e-19
[438. 529.   0.] 0.2952220758335985 -4.0708813403215683e-19
[ 439. -543.    0.] 0.2983790038506946 -1.0701510566896223e-18
[-341. -15

In [11]:
shifts

array([[[   0.,    0.,    0.],
        [   2.,  529.,    0.],
        [  -2., -208.,    0.],
        [ 436.,    1.,    0.],
        [ 438.,  529.,    0.],
        [-291., -101.,    0.],
        [-341., -153.,    0.],
        [-376., -401.,    0.],
        [-288.,  -66.,    0.]],

       [[  -2., -529.,    0.],
        [   0.,    0.,    0.],
        [  -4.,  544.,    0.],
        [ 433., -528.,    0.],
        [ 435.,    0.,    0.],
        [ -66.,   11.,    0.],
        [-399., -130.,    0.],
        [-383.,  359.,    0.],
        [  81.,    0.,    0.]],

       [[   2.,  208.,    0.],
        [   4., -544.,    0.],
        [   0.,    0.,    0.],
        [-126.,  579.,    0.],
        [ 439., -543.,    0.],
        [ 436.,    2.,    0.],
        [-152.,  -74.,    0.],
        [ 430., -439.,    0.],
        [ 404.,  154.,    0.]],

       [[-436.,   -1.,    0.],
        [-433.,  528.,    0.],
        [ 126., -579.,    0.],
        [   0.,    0.,    0.],
        [   2.,  528.,    0.],
  

In [6]:
np.savez_compressed("shifts.npz", shifts=shifts, error=error, phasediff=phasediff)